parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Kernel.php'
      - '../src/DTO/'

  App\Product\Controller\:
    resource: '../src/Product/Controller/'
    tags: ['controller.service_arguments']

  # Interface binding
  App\Product\Repository\ProductRepositoryInterface:
    alias: App\Product\Infrastructure\Repository\ProductORMRepository

when@test:
  services:
    Test\Data\Product\Infrastructure\Repository\:
      resource: '../tests/Data/Product/Infrastructure/Repository/'
      autowire: true
      autoconfigure: true

    App\Product\Repository\ProductRepositoryInterface:
      alias: Test\Data\Product\Infrastructure\Repository\InMemoryProductRepository